INSERT INTO "recommendations" (relatp_type, rcmdn)
VALUES ('fr', 'Grab drinks'),
('fr', 'Grab dinner'),
('fr', 'Catch a show'),
('fr', 'Run a 5k together'),
('fr', 'Plan a vacation together'),
('fr', 'Share an interesting article'),
('fr', 'Send a gift'),
('fam', 'Send a text'),
('fam', 'Share an interesting article'),
('fam', 'Send a gift'),
('fam', 'Comment on a recent post made in Facebook'),
('fam', 'Send a funny story'),
('fam', 'Run a 5k'),
('prf', 'Comment on a recent post made on LinkedIn'),
('prf', 'Grab coffee'),
('prf', 'Share an interesting article'),
('prf', 'Send an email');